version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: liveroomchat_db
    restart: always
    environment:
      POSTGRES_DB: liveroomchat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    network_mode: host
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
